name: Allsafe
favicon: null
layout_spectrum: 0.92786
typography_spectrum: 0.60802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#82a4b9'
    - '#000000'
    - '#303030'
    - '#d64f23'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
